### ISSUE TITLE
Cannot activate the mod

### ISSUE THREAD

**Issue by Ebolavector** [Beaver-Bois-Modding/fs22-tgm#1]
Hello, cannot activate the mod on my game. I'm on the map "la plaine française".

**Comment by Orsa1305** [comment]
same here,  it won't  show  up in the game settings.

**Comment by thedeedawg** [comment]
Thank you for reaching out, and I apologize for the rater late reply here.

With the initial version of the mod (1.0.0.0), there was an issue navigating the settings with a controller as the elements weren't linked together correctly. This could lead to believing that the settings weren't there as the menu would just return the focus to the top before getting to them.

I've just released a new version (1.1.0.0) which not only solves this issue, but also moves the settings to a new custom menu (default keybind is LEFT ALT + 1). The update is not yet live on the ModHub, but it will be soon. Until then, you can find it as a release here on GitHub.

Let me know if you continue to experience issues.
