### ISSUE TITLE
[Improvement] pt-br translation

### ISSUE THREAD

**Issue by Myiamoto86** [Beaver-Bois-Modding/fs22-tgm#4]
[Improvement] pt-br translation

Dear...

I translated your mod into the language of my country and I hope to help it evolve and make it more attractive to more players.

I will be available for future additional changes to your mod. If you have others, and you want, I can translate the others.

Hugs
[locale_br.txt](https://github.com/Beaver-Bois-Modding/fs22-tgm/files/11132867/locale_br.txt)
[modDesc.txt](https://github.com/Beaver-Bois-Modding/fs22-tgm/files/11132868/modDesc.txt)

**Comment by thedeedawg** [comment]
Hi there,

Thank you for your interest in providing a translation for this mod. The modDesc.txt you attached is just the current one, meaning your translation is not in it.

**Comment by Myiamoto86** [comment]
Forgive me for the gaffe.

I'm sending the co
[modDesc.txt](https://github.com/Beaver-Bois-Modding/fs22-tgm/files/11140346/modDesc.txt)
rrect file.

**Comment by thedeedawg** [comment]
Thank you for your contribution. It'll be included in a future release.

For the record, it would be easier if you submit your contributions through a pull request from your own fork of the repository towards the original. You can read more about that here, https://docs.github.com/en/get-started/quickstart/contributing-to-projects. This might differ between projects, but for this particular repository, you should base your branch on the `develop` branch and also make your pull request towards the `develop` branch.

**Comment by Myiamoto86** [comment]
OK. Thanks for the sugestion. I was not aware of this procedure.
